### ISSUE TITLE
Web Client throws error when refreshing with invalid token

### ISSUE THREAD

**Issue by johnpryan** [apptreesoftware/revolution#80]
**Steps to Reproduce**
1. load app (set token expiration to 1 minute)
2. wait for token to expire
3. refresh app

```
Uncaught Unhandled exception:
FormatException: Unexpected character (at character 1)
Invalid token
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1224)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:903)
#3      _parseJson (dart:convert-patch/convert_patch.dart:19)
#4      JsonDecoder.convert (dart:convert/json.dart:501)
#5      JsonCodec.decode (dart:convert/json.dart:127)
#6      UserService._fetchUserJson.<_fetchUserJson_async_body> (package:revolution/src/services/user_service.dart:20:17)
#7      _RootZone.runUnary (dart:async/zone.dart:1404)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._completeWithValue (dart:async/future_impl.dart:477)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _ScheduleImmediateHelper._handleMutation (dart:html:49308)
```

**Comment by johnpryan** [comment]
this can also result in lists not being loaded by RuntimeDataController
